wordBank1 = ("State, The computer has Microsoft Office 365, Chrome, Internet Explorer, etc.","Define, The computer has Microsoft Office 365, which has programmes such as Word, Excel, Access and PowerPoint in it. Internet Explorer and Chrome are also there, which serve as its main web browsers.", "State, State meaning and identify essential qualities.", "Define, State meaning and identify essential qualities.", "Describe, Provide characteristics and features.", "Explain, Relate cause and effect; make the relationships between things evident; provide why and/or how.", "Analyse, Identify components and the relationship between them; draw out and relate implications.", "Justify, Support an argument or conclusion.", "Evaluate, Make a judgement based on criteria; determine the value of." )

wordbank2 = ("Define, The computer has Microsoft Office 365, which has programmes such as Word, Excel, Access and PowerPoint in it. Internet Explorer and Chrome are also there, which serve as its main web browsers.",
                   "Explain, The applications Office 365, Internet Explorer and Chrome are on the computers. Office 365 contains applications such as Word, Excel and Access which are available both at school and online through Internet Explorer and Chrome. Internet Explorer and Chrome are both web browsers, which are not only used to provide access to Office 365, but also to information and YouTube videos to help with assessments from anywhere, at any time.")

wordbank3 = ("Analyse, Office 365, Internet Explorer and Chrome are on the computers. Internet Explorer and Chrome are both web browsers, which provide a graphical interface to the information and content available online. Some of that content includes but is not limited to the Office 365 application suite, allowing students to access Word, Excel, PowerPoint etc anywhere, anytime. These are accessible inside the Office 365 interface through easily-identifiable web-based versions of these applications; the computer-based versions of these applications are more powerful.",
                  "Justify, Office 365, Internet Explorer and Chrome are on the computers. Internet Explorer and Chrome are both web browsers, which provide a graphical interface to the information and content available online. Some of that content includes but is not limited to the Office 365 application suite, allowing students to access Word, Excel, PowerPoint etc anywhere, anytime. This easy access allows students to complete school assessments and tasks without being in any way, shape or form disadvantaged by needing to have the Office suite installed on their own computers, behaving much like the applications on the desktop machines at school.",)


wordbank4 = ("Evaluate, Office 365, Internet Explorer and Chrome are on the computers. Internet Explorer and Chrome are both web browsers, which provide a graphical interface to the information and content available online. Some of that content includes but is not limited to the Office 365 application suite, allowing students to access Word, Excel, PowerPoint etc anywhere, anytime. This easy access allows students to complete school assessments and tasks without being in any way, shape or form disadvantaged by needing to have the Office suite installed on their own computers, behaving much like the applications on the desktop machines at school. The main advantage of this open access is the reduction in gaps between those who have access to the Office suite and those who do not, meaning less excuses for those who may have used this lack of access in the past. However, this also may reduce skill sets or exposure to other application suites such as OpenOffice which some may perceive as a failing of being homogenous",)

